[package]
name = "user-trades"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }

thiserror = "1.0.33"
tokio = "1.20.1"
sqlx = { version = "0.6", features = [ "offline", "runtime-tokio-rustls", "postgres", "decimal", "uuid", "chrono" ] }
uuid = "1.1.2"
tracing = "0.1.36"
serde = "1.0.143"
anyhow = "1.0.63"
rust_decimal = "1.26.1"
rust_decimal_macros = "1.26.1"
futures = "0.3.24"

[dev-dependencies]
anyhow = "1.0.63"
lazy_static = "1.4.0"
