[package]
name = "user-trades"
version = "0.1.0"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }
galoy_client = { path = "../galoy-client", package = "galoy-client" }

thiserror = "1.0.34"
tokio = "1.20.1"
sqlx = { version = "0.6", features = [ "offline", "runtime-tokio-rustls", "postgres", "decimal", "uuid", "chrono", "json" ] }
sqlxmq = { version = "0.4.1", default-features = false, features = [ "runtime-tokio-rustls" ] }
serde_json = "1.0.85"
uuid = "1.1.2"
tracing = "0.1.36"
serde = "1.0.143"
anyhow = "1.0.64"
rust_decimal = {version = "1.26.1", features = ["maths"]}
rust_decimal_macros = "1.26.1"
futures = "0.3.24"

[dev-dependencies]
anyhow = "1.0.64"
lazy_static = "1.4.0"
serial_test = "0.9.0"
chrono = "0.4.22"
