[package]
name = "user-trades"
version = "0.8.1-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }
ledger = { path = "../ledger", package = "stablesats-ledger" }
galoy_client = { path = "../galoy-client", package = "galoy-client" }

thiserror = "1.0.38"
chrono = "0.4"
tokio = "1.26.0"
sqlx = { version = "0.6", features = [ "offline", "runtime-tokio-rustls", "postgres", "decimal", "uuid", "chrono", "json" ] }
sqlxmq = { version = "0.4.1", default-features = false, features = [ "runtime-tokio-rustls" ] }
serde_json = "1.0.93"
uuid = "1.3.0"
tracing = "0.1.37"
serde = "1.0.152"
anyhow = "1.0.69"
rust_decimal = "1.28.1"
rust_decimal_macros = "1.28.1"
futures = "0.3.26"
serde_with = "2.2.0"

[dev-dependencies]
anyhow = "1.0.69"
serial_test = "1.0.0"
