[package]
name = "user-trades"
version = "0.3.20-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }
galoy_client = { path = "../galoy-client", package = "galoy-client" }

thiserror = "1.0.37"
chrono = "0.4"
tokio = "1.23.0"
sqlx = { version = "0.6", features = [ "offline", "runtime-tokio-rustls", "postgres", "decimal", "uuid", "chrono", "json" ] }
sqlxmq = { version = "0.4.1", default-features = false, features = [ "runtime-tokio-rustls" ] }
serde_json = "1.0.91"
uuid = "1.2.2"
tracing = "0.1.37"
serde = "1.0.150"
anyhow = "1.0.68"
rust_decimal = "1.26.1"
rust_decimal_macros = "1.26.1"
futures = "0.3.25"
serde_with = "2.1.0"

[dev-dependencies]
anyhow = "1.0.68"
lazy_static = "1.4.0"
serial_test = "0.10.0"
