[package]
name = "okex-price"
version = "0.1.2-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.31"
tokio = { version = "1.20.1", features = ["full"] }
tokio-tungstenite = { version = "0.17.2", features = ["native-tls"]  }
url = { version = "2.2.2", features = ["serde"] }
shared = { path = "../shared" }
rust_decimal = "1.26.0"

[dev-dependencies]
anyhow = "1.0.59"
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
