[package]
name = "okex-price"
version = "0.3.11-dev"
edition = "2021"
authors = ["Justin Carter <justin@galoy.io>"]
license = "MIT"
repository = "https://github.com/GaloyMoney/stablesats-rs"
description = "Publishes okex price feed to redis"

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }

futures = "0.3.24"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
tokio-tungstenite = { version = "0.17.2", features = ["rustls-tls-webpki-roots"]  }
url = { version = "2.3.1", features = ["serde"] }
rust_decimal = "1.26.1"
tracing = "0.1.37"

[dev-dependencies]
anyhow = "1.0.65"
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
