version: "2"
services:
  integration-deps:
    image: busybox
    depends_on:
    - redis
  redis:
    image: bitnami/redis:6.2
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  integration-tests:
    image: us.gcr.io/galoy-org/rust-concourse
    depends_on:
    - integration-deps
    command: ["make","test-in-ci"]
    environment:
    - REDIS_HOST=redis
    working_dir: /repo
    volumes:
      - ./:/repo
