version: "3"
services:
  integration-deps:
    image: busybox
    depends_on:
    - otel-agent
    - postgres
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg
  integration-tests:
    image: us.gcr.io/galoy-org/rust-concourse
    depends_on:
    - integration-deps
    command: ["make","test-in-ci"]
    env_file:
      - ${TMP_ENV_CI:-.env.ci}
    environment:
    - RUST_BACKTRACE=1
    - PG_HOST=postgres
    - PG_PORT=5432
    - GALOY_GRAPHQL_URI=https://api.staging.galoy.io/graphql
    working_dir: /repo
    volumes:
      - ./:/repo
      - cargo-cache:/usr/local/cargo
  otel-agent:
    image: otel/opentelemetry-collector-contrib:0.57.2
    command: ["--config=/etc/otel-agent-config.yaml"]
    environment:
    - HONEYCOMB_DATASET=${HONEYCOMB_DATASET}
    - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
    volumes:
      - ./dev/otel-agent-config.yaml:/etc/otel-agent-config.yaml
volumes:
  cargo-cache:
