[package]
name = "galoy-client"
version = "0.1.0"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
futures = "0.3.23"
graphql_client = {version = "0.11.0", features = ["reqwest"]}
reqwest = {version = "0.11.11", features = ["json", "rustls-tls-webpki-roots"]}
serde = { version = "1.0.144", features = ["derive"] }

thiserror = "1.0.34"
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
tracing = "0.1.36"
rust_decimal = "1.26.1"
rust_decimal_macros = "1.26.1"

[dev-dependencies]
anyhow = "1.0.64"
tokio = { version = "1.20.1", features = ["macros"] }
