[package]
name = "galoy-client"
version = "0.4.2-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
futures = "0.3.25"
graphql_client = {version = "0.12.0", features = ["reqwest"]}
reqwest = { version = "0.11.14", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"

thiserror = "1.0.38"
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
tracing = "0.1.37"
rust_decimal = "1.26.1"
rust_decimal_macros = "1.28.0"
opentelemetry = "0.18.0"
tracing-opentelemetry = "0.18.0"
opentelemetry-http = "0.7.0"

[dev-dependencies]
anyhow = "1.0.68"
tokio = { version = "1.24.2", features = ["macros"] }
