[package]
name = "galoy-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.23"
graphql_client = {version = "0.11.0", features = ["reqwest"]}
reqwest = {version = "0.11.11", features = ["json"]}
serde = { version = "1.0.144", features = ["derive"] }

thiserror = "1.0.34"
itertools = "0.10.2"
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
rust_decimal = "1.26.1"
rust_decimal_macros = "1.26.1"

[dev-dependencies]
anyhow = "1.0.64"
tokio = { version = "1.20.1", features = ["macros"] }
