[package]
name = "galoy-client"
version = "0.3.18-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
futures = "0.3.25"
graphql_client = {version = "0.11.0", features = ["reqwest"]}
reqwest = { version = "0.11.13", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"

thiserror = "1.0.37"
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
tracing = "0.1.37"
rust_decimal = "1.26.1"
rust_decimal_macros = "1.26.1"
opentelemetry = "0.18.0"
tracing-opentelemetry = "0.18.0"
opentelemetry-http = "0.7.0"

[dev-dependencies]
anyhow = "1.0.66"
tokio = { version = "1.22.0", features = ["macros"] }
