[package]
name = "okex-client"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.11", default-features = false, features = ["json", "rustls-tls"] }
thiserror = "1.0.35"
tokio = "1.20.1"
ring = "0.16.20"
data-encoding = "2.3.2"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
serde_yaml = "0.9.11"
rust_decimal = "1.26.1"
governor = "0.4.2"
lazy_static = "1.4.0"
rust_decimal_macros = "1.26.1"

[dev-dependencies]
anyhow = "1.0.65"
serial_test = "*"
