[package]
name = "okex-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.11"
thiserror = "1.0.32"
tokio = "1.20.1"
shared = { path = "../shared" }
ring = "0.16.20"
data-encoding = "2.3.2"

[dev-dependencies]
serde = {version = "1.0.142", features = ["derive"]}
serde_json = "1.0.83"
anyhow = "1.0.59"
