[package]
name = "okex-client"
version = "0.3.11-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.12", default-features = false, features = ["json", "rustls-tls"] }
thiserror = "1.0.37"
tokio = "1.21.2"
ring = "0.16.20"
data-encoding = "2.3.2"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
serde_yaml = "0.9.13"
rust_decimal = "1.26.1"
governor = "0.5.0"
lazy_static = "1.4.0"
rust_decimal_macros = "1.26.1"
rand = "0.8.5"

[dev-dependencies]
anyhow = "1.0.65"
serial_test = "*"
