[package]
name = "okex-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.11"
thiserror = "1.0.32"
tokio = "1.20.1"
shared = { path = "../shared", package = "stablesats-shared" }
ring = "0.16.20"
data-encoding = "2.3.2"
serde = {version = "1.0.142", features = ["derive"]}
serde_json = "1.0.83"
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
serde_yaml = "0.9.4"

anyhow = "1.0.61"
