[package]
name = "stablesats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
price-server = { path = "../price-server" }

anyhow = "1.0.59"
clap = { version =  "3.2", features = ["derive"] }
serde = { version = "1.0.141", features = ["derive"] }
serde_yaml = "0.9.4"
tokio = "1.20.1"
futures = "0.3.21"
