[package]
name = "stablesats"
version = "0.1.3-dev"
edition = "2021"
authors = ["Justin Carter <justin@galoy.io>"]
license = "MIT"
repository = "https://github.com/GaloyMoney/stablesats-rs"
description = "The stablesats cli binary"

[dependencies]
shared = { path = "../shared" }
price-server = { path = "../price-server" }
okex-price = { path = "../okex-price" }

anyhow = "1.0.59"
clap = { version =  "3.2", features = ["derive", "env"] }
serde = { version = "1.0.141", features = ["derive"] }
serde_yaml = "0.9.4"
tokio = "1.20.1"
futures = "0.3.21"
tonic = "0.8.0"
url = { version = "2.2.2", features = ["serde"] }
rust_decimal = "1.26.0"
