[package]
name = "stablesats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }

anyhow = "1.0.60"
clap = { version =  "3.2", features = ["derive"] }
serde = { version = "1.0.141", features = ["derive"] }
serde_yaml = "0.9.4"
tokio = "1.20.1"
