[package]
name = "stablesats"
version = "0.3.8-dev"
edition = "2021"
authors = ["Justin Carter <justin@galoy.io>"]
license = "MIT"
repository = "https://github.com/GaloyMoney/stablesats-rs"
description = "The stablesats cli binary"

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }
price-server = { path = "../price-server" }
user-trades = { path = "../user-trades" }
galoy-client = { path = "../galoy-client" }
okex-client = { path = "../okex-client" }
hedging = { path = "../hedging" }
okex-price = { path = "../okex-price" }

anyhow = "1.0.65"
clap = { version =  "3.2", features = ["derive", "env"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.9.13"
tokio = "1.21.2"
futures = "0.3.24"
tonic = "0.8.1"
url = { version = "2.3.1", features = ["serde"] }
rust_decimal = "1.26.1"
opentelemetry = "0.18.0"
tracing = "0.1.36"
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-tokio"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
tracing-opentelemetry = "0.18.0"
axum = "0.5.16"
