[package]
name = "price-server"
version = "0.5.5-dev"
edition = "2021"
authors = ["Justin Carter <justin@galoy.io>"]
license = "MIT"
repository = "https://github.com/GaloyMoney/stablesats-rs"
description = "Server that exposes prices for hedging"

[features]

fail-on-warnings = []

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }

chrono = { version = "0.4", features = [
    "clock",
    "serde",
], default-features = false }
prost = "0.11"
tonic = "0.8"
axum-core = "0.3.2"
tokio = "1.24.2"
futures = "0.3.25"
thiserror = "1.0.38"
serde = { version = "1.0.152", features = ["derive"] }
rust_decimal = "1.25.0"
tracing = "0.1.37"
opentelemetry = { version = "0.18.0", features = ["trace"] }
tracing-opentelemetry = "0.18.0"
rust_decimal_macros = "1.28.0"
rusty-money = "0.4.1"
serde_with = { version = "2.2.0", features = ["chrono_0_4"] }
async-trait = "0.1.64"

[build-dependencies]
protobuf-src = { version = "1.1.0" }
tonic-build = { version = "0.8", features = ["prost"] }

[dev-dependencies]
anyhow = "1.0.68"
serde = "1.0.152"
serde_json = "1.0.91"
