[package]
name = "price-server"
version = "0.3.6-dev"
edition = "2021"
authors = ["Justin Carter <justin@galoy.io>"]
license = "MIT"
repository = "https://github.com/GaloyMoney/stablesats-rs"
description = "Server that exposes prices for hedging"

[features]

fail-on-warnings = []

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }

chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
prost = "0.11"
tonic = "0.8"
axum-core = "0.2.8"
tokio = "1.21.2"
futures = "0.3.24"
thiserror = "1.0.37"
serde = "1.0.145"
rust_decimal = "1.25.0"
tracing = "0.1.36"
opentelemetry = { version = "0.18.0", features = ["trace"] }
tracing-opentelemetry = "0.18.0"
rust_decimal_macros = "1.26.1"
rusty-money = "0.4.1"

[build-dependencies]
protobuf-src = { version = "1.1.0" }
tonic-build = { version = "0.8", features = ["prost"] }

[dev-dependencies]
anyhow = "1.0.65"
serde = "1.0.145"
serde_json = "1.0.85"
