[package]
name = "price-server"
version = "0.1.0"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
shared = { path = "../shared" }

prost = "0.10.4"
tonic = "0.7.2"

[build-dependencies]
tonic-build = { version = "0.7.2", features = ["prost"] }
