[package]
name = "price-server"
version = "0.9.2"
edition = "2021"
authors = ["Justin Carter <justin@galoy.io>"]
license = "MIT"
repository = "https://github.com/GaloyMoney/stablesats-rs"
description = "Server that exposes prices for hedging"

[features]

fail-on-warnings = []

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }

chrono = { version = "0.4", features = [
    "clock",
    "serde",
], default-features = false }
prost = "0.11"
tonic = "0.8"
axum-core = "0.3.3"
tokio = "1.26.0"
futures = "0.3.27"
thiserror = "1.0.39"
serde = { version = "1.0.156", features = ["derive"] }
rust_decimal = "1.28.1"
tracing = "0.1.37"
opentelemetry = { version = "0.18.0", features = ["trace"] }
tracing-opentelemetry = "0.18.0"
rust_decimal_macros = "1.28.1"
rusty-money = "0.4.1"
serde_with = { version = "2.3.1", features = ["chrono_0_4"] }
async-trait = "0.1.66"

[build-dependencies]
protobuf-src = { version = "1.1.0" }
tonic-build = { version = "0.8", features = ["prost"] }

[dev-dependencies]
anyhow = "1.0.69"
serde = "1.0.156"
serde_json = "1.0.93"
