[package]
name = "price-server"
version = "0.1.8-dev"
edition = "2021"
authors = ["Justin Carter <justin@galoy.io>"]
license = "MIT"
repository = "https://github.com/GaloyMoney/stablesats-rs"
description = "Server that exposes prices for hedging"

[features]

fail-on-warnings = []

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }

chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
prost = "0.11"
tonic = "0.8"
tokio = "1.20.1"
futures = "0.3.21"
thiserror = "1.0.31"
serde = "1.0.143"
rust_decimal = "1.25.0"

[build-dependencies]
protobuf-src = { version = "1.0.5" }
tonic-build = { version = "0.8", features = ["prost"] }

[dev-dependencies]
anyhow = "1.0.60"
serde = "1.0.143"
serde_json = "1.0.82"
