[package]
name = "stablesats-ledger"
version = "0.5.7-dev"
edition = "2021"


[features]

fail-on-warnings = []

[dependencies]
sqlx-ledger = "0.3"

chrono = "0.4.23"
rust_decimal = "1.28.0"
rust_decimal_macros = "1.28.0"
serde = "1.0.152"
serde_json = "1.0.91"
sqlx = { version = "0.6", features = [ "offline", "runtime-tokio-rustls", "postgres", "decimal", "uuid", "chrono"] }
thiserror = "1.0.38"
tracing = "0.1.37"
uuid = "1.3.0"

[dev-dependencies]
anyhow = "1.0.68"
tokio = "1.25.0"
