[package]
name = "hedging"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

fail-on-warnings = []

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }

serde = "1.0.144"
serde_json = "1.0.85"
tokio = "1.20.1"
futures = "0.3.24"
thiserror = "1.0.33"
opentelemetry = { version = "0.17.0", features = ["trace"] }
tracing-opentelemetry = "0.17.4"
tracing = "0.1.36"

[dev-dependencies]
anyhow = "1.0.63"
