[package]
name = "hedging"
version = "0.5.3"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }
okex-client = { path = "../okex-client" }
bitfinex-client = { path = "../bitfinex-client" }
galoy-client = { path = "../galoy-client" }

rust_decimal_macros = "1.28.0"
serde = "1.0.152"
serde_json = "1.0.91"
tokio = "1.24.2"
futures = "0.3.25"
thiserror = "1.0.38"
opentelemetry = { version = "0.18.0", features = ["trace"] }
tracing-opentelemetry = "0.18.0"
tracing = "0.1.37"
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
sqlx = { version = "0.6", features = [ "offline", "runtime-tokio-rustls", "postgres", "decimal", "uuid", "chrono"] }
sqlxmq = { version = "0.4.1", default-features = false, features = [ "runtime-tokio-rustls" ] }
rust_decimal = "1.26.1"
uuid = "1.2.2"
serde_with = { version = "2.2.0", features = ["chrono_0_4"] }

[dev-dependencies]
anyhow = "1.0.68"
serial_test = "*"
