[package]
name = "kollider-price"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.25"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["full"] }
tokio-tungstenite = { version = "0.17.2", features = [
    "rustls-tls-webpki-roots",
] }
shared = { path = "../shared", package = "stablesats-shared" }
thiserror = "1.0.37"
rust_decimal = "1.26.1"


[dev-dependencies]
anyhow = "1.0.66"
chrono = { version = "0.4", features = [
    "clock",
    "serde",
], default-features = false }
