[package]
name = "stablesats-shared"
version = "0.3.5-dev"
edition = "2021"
authors = ["Justin Carter <justin@galoy.io>"]
license = "MIT"
repository = "https://github.com/GaloyMoney/stablesats-rs"
description = "Code shared between stablesats packages"

[features]

fail-on-warnings = []

[dependencies]
# setting default-features = false to not include vulnerable time crate
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
fred = { version = "5.2.0", features = ["subscriber-client"] }
futures = "0.3.24"
opentelemetry = "0.18.0"
rust_decimal = "1.26.1"
rust_decimal_macros = "1.26.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
thiserror = "1.0.36"
tokio = "1.20.1"
tracing = "0.1.36"
tracing-opentelemetry = "0.18.0"
uuid = { version = "1.1.2", features = ["v4", "serde"] }
governor = "0.5.0"
lazy_static = "1.4.0"
serde_with = "2.0.1"

[dev-dependencies]
anyhow = "1.0.65"
