[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
anyhow = "1.0.58"
chrono = { version = "0.4.19", features = ["serde"] }
fred = { version = "5.1.0", features = ["subscriber-client"] }
futures = "0.3.21"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.31"
tokio = "1.20.1"
uuid = { version = "1.1.2", features = ["v4", "serde"] }
