#@ load("@ytt:data", "data")

#@ load("vendor/pipeline-fragments.lib.yml",
#@   "rust_check_code",
#@   "rust_integration_test",
#@   "repo_resource",
#@   "pipeline_tasks_resource",
#@   "slack_resource_type",
#@   "slack_resource"
#@ )

groups:
- name: stablesats-rs
  jobs:
    - check-code
    - test-integration

jobs:
- #@ rust_check_code()
- #@ rust_integration_test()

resources:
- #@ repo_resource()
- #@ pipeline_tasks_resource()
- #@ slack_resource()

resource_types:
- #@ slack_resource_type()
