apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- path: vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: dbb50e4c6037f8f38b2a0c88abda5688afca48cb
    includePaths:
    - shared/**/*
    newRootPath: shared
