name: "Dependencies integration Tests"

on:
  pull_request_target:
    types: [labeled]

jobs:
  dependencies-integration:
    name: Dependencies Integration Test
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - uses: actions/checkout@v2
      - name: Run integration tests
        env:
          OKEX_API_KEY: ${{ secrets.OKEX_API_KEY }}
          OKEX_PASSPHRASE: ${{ secrets.OKEX_PASSPHRASE }}
          OKEX_SECRET_KEY: ${{ secrets.OKEX_SECRET_KEY }}
          BITFINEX_API_KEY: ${{ secrets.BITFINEX_API_KEY }}
          BITFINEX_SECRET_KEY: ${{ secrets.BITFINEX_SECRET_KEY }}
        run: docker compose -f docker-compose.yml run integration-tests
